name: Python IA CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 dvc

      - name: Ejecutar Linter (flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Ejecutar pruebas (pytest)
        run: |
          python -m pytest tests/

      - name: Validar Versionado DVC
        run: |
          test -f dataset/dataset.csv.dvc
          test -f modelo/modelo.pkl.dvc
          dvc version
          echo "Dataset y modelo versionados correctamente con DVC."

      - name: Build
        run: |
          python -m compileall .