name: Python IA CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 dvc

      - name: Ejecutar Linter (flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Ejecutar pruebas (pytest)
        run: |
          python -m pytest tests/

      - name: Validar Dataset
        run: |
          test -f dataset/dataset.csv

      - name: Validar Modelo
        run: |
          test -f modelo/modelo.pkl

      - name: Validación IA
        run: |
          echo "Dataset y modelo encontrados correctamente."

      - name: Build
        run: |
          python -m compileall .